name: backup
networks:
  default:
    name: backup_default
services:
  rclone:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MONITORING_URL=${MONITORING_URL}
    networks:
      default: null
    restart: unless-stopped
    volumes:
      - bind:
          create_host_path: true
        read_only: true
        source: /vm/data-root/volumes
        target: /vm/data-root/volumes
        type: bind
      - type: volume
        source: config
        target: /config/rclone
        volume: {}
volumes:
  config:
    name: backup_config